# =============================================
# Configuration schema to set translatable block
# =============================================
#
# Example https://www.calibrate.be/news/translating-custom-block-plugin-configuration
#
